apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pod-defaults
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/vmallya-123/argoflow
    targetRevision: argoflow-test
    path: kubeflow/notebooks/pod-defaults
    kustomize:
      version: v4.0.5
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
